custom: [ Paypal: 'www.paypal.com/donate/?hosted_button_id=LAQVVT4SNVNNL', AdFoc.us:'adfoc.us/70081781929588', 'weakermumrespect.com/c8px60a73a?key=39485c7d3834c441ba588c954ce2c2aa',
'publishers.adsterra.com/referral/ejkPuis51r']
