
#####################################################################################
#Mod settings such as speed in different situations
#####################################################################################
[autorun]
	#
	# Creative flight speed
	#Range: 0.0010000000474974513 ~ 1.0
	flightSpeed = 1
	#
	# Mounted riding speed, while riding any Living Entity 
	#Range: 0.0010000000474974513 ~ 1.0
	ridingSpeed = 1
	#
	# Boating speed (any entity that extends BoatEntity) 
	#Range: 0.0010000000474974513 ~ 1.0
	boatingSpeed = 1
	#
	# Allowed while using Elytra
	allowElytra = true
	#
	# Walking speed 
	#Range: 0.0010000000474974513 ~ 1.0
	walkingSpeed = 1

