
#Keystrokes Settings
[general]
	#Defines whether or not to show the movement buttons in the HUD.
	show-movement = true
	#Defines whether or not to show the mouse buttons in the HUD.
	show-mouse = true
	#Defines whether or not to show the space bar in the HUD.
	show-spacebar = true
	#Defines whether or not to display the CPS
	#(clicks-per-second) on the mouse part.
	#Allowed Values: ALWAYS, ON_CLICK, NEVER
	show-cps = "ALWAYS"

	#Keystrokes Design
	[general.looks]
		#If enabled, the HUD will wave in all colors of the rainbow.
		rainbow = false
		#If enabled, the HUD text with show with a text shadow.
		text-shadow = false
		#Choose to display the HUD keys as arrows or key names.
		#Allowed Values: WASD, ARROWS
		key-display = "WASD"
		#If enabled, all overlay huds will sync color with the Default overlay.
		sync-colors = false

